# Two Suns
bodies:
  - Name: Body1
    Mass: 90.9891E34
    Radius: 69570E6
    Position: -349597870700, 50E10, 0
    Velocity: -300E3,0E3, -6000E3
    Color: ff0000
    Type: Star
  - Name: Body2
    Mass: 90.9891E34
    Radius: 69570E6
    Position: 349597870700, 50E10, 0
    Velocity: 300E3, 0E3, 6000E3
    Color: ff0000